// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcbeSijbJTrNDuh7CH4w0ys5d7AIzUSKo',
    appId: '1:1023095960523:android:69f4461bd44ede3d73fc4e',
    messagingSenderId: '1023095960523',
    projectId: 'foot-fetish-9a250',
    databaseURL: 'https://foot-fetish-9a250-default-rtdb.firebaseio.com',
    storageBucket: 'foot-fetish-9a250.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3kN2I_F5USHqdTHjNS--dPYBPCcx11Gk',
    appId: '1:1023095960523:ios:35f67ee8c7cea47773fc4e',
    messagingSenderId: '1023095960523',
    projectId: 'foot-fetish-9a250',
    databaseURL: 'https://foot-fetish-9a250-default-rtdb.firebaseio.com',
    storageBucket: 'foot-fetish-9a250.appspot.com',
    iosClientId: '1023095960523-t3fhthflro6m25sq4l7fo9o46pc6vbh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoes',
  );
}
